### ISSUE TITLE
Create project ROADMAP.md

### ISSUE THREAD

**Issue by McCodeman** [anuvu/zot#154]
As a project viewer, I would like to quickly understand the future plans for the project.

Acceptance Criteria:
* [ ] Create ROADMAP.md in root of project. List upcoming features and architectural changes including expected release milestones.
* [ ] Include relevant alignment to dependent projects or project dependencies in the ecosystem.
* [ ] Create matching milestones for immediate future work in project.
* [ ] Map roadmap features to Issues and associate to milestones or backlog priority
* [ ] Include or link to document describing release cadence.
* [ ] Link to ROADMAP.md from README.md
